name: aquacropgrid-preproc
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - xarray
  - shapely
  - requests
  - geopandas
  - rasterio
  - pandas
  - conda-forge::cdsapi
  - netcdf4
  - conda-forge::rioxarray
  - owslib
  - conda-forge::soilgrids
