name: aquacropgrid-preproc
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - xarray
  - shapely
  - requests
  - geopandas
  - rasterio
  - pandas
  - cdsapi
  - netcdf4
  - rioxarray
  - owslib
  - soilgrids
  - pip
  - pip:
    - aquacrop
    - dnspython
